### ISSUE TITLE
cost-benefit on requests vs httplib: speed and connection timeouts

### ISSUE THREAD

**Issue by ryran** [ravello/python-sdk#12]
Hey folks. As you may or may not be aware, at Red Hat we built a tool (https://github.com/ryran/ravshello) that uses the sdk to provide a cli to manage apps and vms via Ravello.

Today was the first time I released a new version to any internal folks since pull #7 ... and got some pretty serious feedback immediately from one of the training content developers that's using it.

I assume you started using **requests** because it made it easier to do proxy stuff? In my own benchmarking (see https://github.com/ryran/ravshello/issues/12), it's crystal clear to me that **requests** is markedly slower than **httplib**. Kind of a bummer, but honestly, I don't care.

What I'm more conerned about -- and would request your expertise -- is understanding why `ravello_sdk.RavelloClient()` behaves differently (**in terms of the connection timing out**) between the two (httplib vs requests). To quote myself from the above-linked issue:

> *Today Hayley was logged in to the old version from the morning all the way until 4 in the afternoon, doing commands sporadically (every hour or so). No problems. That's typical. Occasionally a command fails (not even once a day I think) but simply trying the same command again always succeeds. There's never a need to quit and login again.*
> 
> *After switching to the new version around 4pm, it became pretty clear that something big was different -- within minutes of inactivity she got the following traceback and had to quit out of ravshello to login again.*

I wish this could be explained by a commit changing the `RavelloClient.deault_timeout` attr, but that has stayed the same between versions. ... *(Aside: I don't quite understand what that does anyway, given my experience that I can stay logged in via one `RavelloClient()` object all day.)*

I'm not asking you to change anything in the sdk. Any advice for me though?

**Comment by gilhoffer** [comment]
Hey Ryan,
The motivation to move to requests was indeed in order to more easily support proxy+https connections.
I'm less worried about the lower performance, but the timeouts are of course an issue....
We will look at this and update as soon as we have something.
@hadard , @elayeek , please note this one.

**Comment by ryran** [comment]
Thanks for the response @gilhoffer.
I want to add one more comment:

I would like to understand why httplib and requests handle the following differently:

1. I logged in with a `RavelloClient()` object, using both the older (httplib) and newer (requests) sdk
2. I fell asleep
3. I came back to it 10 hours later
    - The older sdk had no problem immediately responding to API calls
    - The newer sdk failed with a traceback, i.e.:

```
  File "ravello_sdk.py", line 456, in get_applications
    apps = self.request('GET', '/applications')
  File "ravello_sdk.py", line 325, in request
    response = self._request(method, path, body, headers)
  File "ravello_sdk.py", line 386, in _request
    raise RavelloError('got status {0} ({1}/{2})' .format(status, code, msg))
RavelloError: got status 401 (unknown/unknown)
```

**Comment by elayeek** [comment]
Yes, it seems that it is not keeping the connection alive and then tries to send a request.
I am looking into it.

**Comment by ryran** [comment]
#22

**Comment by ryran** [comment]
Did some benchmarking today with the new version (few weeks ago) that we have thanks to @elayeek and it's finally comparable to the old httplib. Sweeeeet. Thanks Elaye.
