### ISSUE TITLE
RavelloClient.get_vnc_url() always fails

### ISSUE THREAD

**Issue by ryran** [ravello/python-sdk#13]
Traceback:

```
>>> import ravello_sdk ; r = ravello_sdk.RavelloClient()
>>> user = 'xxxx' ; passwd = 'xxxxx'
>>> r.login(user, passwd)
>>> app = 54264578
>>> vm = 169016025
>>> r.get_vm(app, vm, aspect='deployment')['state']
u'STARTED'
>>> r.get_vnc_url(app, vm)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ravello_sdk.py", line 620, in get_vnc_url
    return url.decode('iso-8859-1')
AttributeError: 'NoneType' object has no attribute 'decode'
```

Relevant code from sdk:

```
def get_vnc_url(self, app, vm):
    """Get the VNC URL for the VM with ID *vm* in the application with ID *app*."""
    if isinstance(app, dict): app = app['id']
    if isinstance(vm, dict): vm = vm['id']
    headers = [('Accept', 'text/plain')]
    url = self.request('GET', '/applications/{0}/vms/{1}/vncUrl'.format(app, vm),
                       headers=headers)
    return url.decode('iso-8859-1')
```

Works just fine if I use the code from before pull #7 (i.e., https://github.com/ryran/python-sdk/tree/experimental).

Honestly, I haven't bothered to look into it because I'm gonna stick with httplib for now. There are too many other issues.

For my reference: https://github.com/ryran/ravshello/issues/13

**Comment by gilhoffer** [comment]
@elayeek , please note this one as well.
10x,
Gil

**Comment by ryran** [comment]
Well I just spent a little while playing with this ... trying to figure it out ... but I didn't get anywhere.

I *did* notice that `RavelloClient.get_vnc_url()` is the only method (except `_login()`) which makes use of the `headers=` param of `RavelloClient.request()` ... so ... yeah.

**Comment by ryran** [comment]
Fixed with @elayeek's commits in the last month.

**Comment by hh-yow** [comment]
This issue is reproducible now again.

- Python: 3.4.4
- Ravello SDK: 1.27

```
File "C:\Python34\lib\site-packages\ravello_sdk.py", line 684, in get_vnc_url
    return url.decode('iso-8859-1')
AttributeError: 'str' object has no attribute 'decode'
```
