### ISSUE TITLE
Can't get RavelloClient.create_user() to work

### ISSUE THREAD

**Issue by ryran** [ravello/python-sdk#19]
```
>>> r
r: <ravello_sdk.RavelloClient object at 0x156d810>
>>> r.get_users()[0]['name']
u'Ryan'
>>> req = {'email': "ryan@b19.org", 'name': "Ryran", 'surname': "Aroha"}
>>> user = r.create_user(req)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ravello_sdk.py", line 820, in create_user
    return self.request('POST', '/users', user)
  File "ravello_sdk.py", line 333, in request
    response = self._request(method, path, body, headers)
  File "ravello_sdk.py", line 401, in _request
    raise RavelloError('got status {0} ({1}/{2})' .format(status, code, msg))
ravello_sdk.RavelloError: got status 405 (unknown/unknown)
```

**Comment by ryran** [comment]
PS: I first tried this months ago. I've never been able to get it to work, despite trying multiple different email addresses. (Note that I can then turn around and use the same email to do an invite from the web UI.) Any suggestions?

**Comment by hadard** [comment]
To create users in the organization, path should be:  /organizations/:orgid/users.  Looks like the sdk uses the wrong path in create_user function.
see: http://www.ravellosystems.com/developers/rest-api/users

See also: http://www.ravellosystems.com/developers/rest-api/organizations for getting current logged-in user organization.

**Comment by ryran** [comment]
You're right of course @hadard ... I should have noticed that. I can fix it of course, but ... why? Why does the API behave this way? Why are all the other user commands but PUT accessible from /users?

**Comment by ryran** [comment]
Well I added 2 new methods: `get_organization()` and `update_organization()`. Then tweaked `create_user()` to use the orgid returned by `get_organization()`.

```
>>> r
<ravello_sdk.RavelloClient object at 0xf98790>
>>> r.get_organization()['organizationName']
u'Red Hat Global Support Services'
>>> req = {'email': "ryan@b19.org", 'name': "Ryran", 'surname': "Aroha"}
>>> user = r.create_user(req)
>>> a(user)
{
    "activateTime": null, 
    "surname": "Aroha", 
    "name": "Ryran", 
    "roles": [
        "USER"
    ], 
    "activated": false, 
    "enabled": true, 
    "id": 54296591, 
    "_href": "/organizations/49381386/users/54296591", 
    "invitationTime": "1422374299462", 
    "organization": 49381386, 
    "email": "ryan@b19.org", 
    "uuid": "ca680382-2500-42de-95cf-e222425d6b78"
}
```

Pull request forthcoming, but I'm not sure if you guys are gonna like it.

**Comment by hadard** [comment]
The reason it's under /organization is that the request is to create user under that organization and REST wise you need to mention the full path of the resource. I think that creating the shortcut you suggest in python sdk is legit.
 
Some more background: for example you have /organizations/:orgId/blueprints which returns just the organization blueprints (without the public blueprints) and /blueprints that returns all the accessible blueprints. In this case, POST to /blueprints will create blueprint in the organization but in the future you probably be able to create "shared" blueprint so it's reasonable to POST to the "general" location. But we don't plan to allow to users to create users in some "shared" place.

**Comment by ryran** [comment]
@hadard : Thanks for the explanation. I had forgotten about the idea of public blueprints.
