### ISSUE TITLE
RavelloClient.get_vnc_url() always fails 

### ISSUE THREAD

**Issue by hh-yow** [ravello/python-sdk#48]
The issue which is explained in https://github.com/ravello/python-sdk/issues/13 is reproducible again now:
- Python: 3.4.4
- Ravello SDK: 1.27

```
File "C:\Python34\lib\site-packages\ravello_sdk.py", line 684, in get_vnc_url
    return url.decode('iso-8859-1')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by gilhoffer** [comment]
Thanks for reporting this.
It looks like a python3 specific issue ; we'll look into it.
In the meanwhile, you can use python2.

Thanks,
Gil
