### ISSUE TITLE
PyPi version outdated

### ISSUE THREAD

**Issue by smarlowucf** [ravello/python-sdk#55]
The package index has not been updated with the most recent version 2.5.

**Comment by smarlowucf** [comment]
Can version 2.6 be pushed to PyPI?

**Comment by gilhoffer** [comment]
@johnyzed , @zoza - can one of you please handle it?

10x

**Comment by johnyzed** [comment]
Done.
Version 2.7 has been pushed

**Comment by smarlowucf** [comment]
Thanks @johnyzed @gilhoffer !
